apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: cni
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cni
  policy:
    semver:
      range: '>= 3.0.0 <4.0.0'