apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: ">=16.7.0"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    prometheus:
      prometheusSpec:
        secrets: [ "etcd-client-cert" ]
      ingress:
        enabled: true
        hosts: [ "prometheus.mydns.dog" ]
        pathType: ImplementationSpecific
    kubeControllerManager:
      service:
        port: 10257
        targetPort: 10257
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kubeScheduler:
      service:
        targetPort: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kubeEtcd:
      serviceMonitor:
        scheme: https
        insecureSkipVerify: false
        # included as a SAN via kubeadm
        serverName: localhost
        caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
        certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
        keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
    grafana:
      adminPassword: "hmmm-doy"
      ingress:
        enabled: true
        hosts: [ "grafana.mydns.dog" ]
        pathType: ImplementationSpecific
    alertmanager:
      ingress:
        enabled: true
        hosts: [ "alertmanager.mydns.dog" ]
        pathType: ImplementationSpecific
      alertmanagerSpec:
        externalUrl: "http://alertmanager.mydns.dog"
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['alertname', 'job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'null'
          routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
        receivers:
        - name: 'null'