apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - podinfo.yaml
  - vmware-tanzu.yaml
  - minio.yaml
  - prometheus-community.yaml
  - ingress-nginx.yaml
  - jimangel-charts.yaml